name: Manual Dispatch Workflow

on:
  workflow_dispatch:

env:
    aws_key: ${{ secrets.AWS_KEY }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets
        run: |
            echo "${{ env.aws_key }}" >> newfile
            cat newfile
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: single-file-artifact
            path: newfile
            
  download-and-use:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: single-file-artifact
          path: .
      - name: Show downloaded file
        run: cat newfile