name: Manual Dispatch Workflow

on:
  workflow_dispatch:

env:
    aws_key: ${{ secrets.AWS_KEY }}

jobs:
  run-manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets
        run: |
            echo "${{ env.aws_key }}" >> newfile
            cat newfile
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: single-file-artifact
            path: newfile
